### ISSUE TITLE
When will your official release be released?

### ISSUE THREAD

**Issue by ghd258** [EnterpriseLibrary/common-infrastructure#2]
When will your official release be released? Suggestion: the Net Framework version of Enterprise Library is available with Microsoft official. The version you are developing now suggests that a single Net Core version is better, and you don't have to consider so many compatibility in your development.
![20180604092327](https://user-images.githubusercontent.com/4811375/40894059-67fa3a9c-67d9-11e8-8c1e-4acadc655cb0.jpg)

**Comment by Chavoshi** [comment]
This community is going to be the official community of **Enterprise Library** and it has to support all the available frameworks.

I do not have any estimation when it is going to be released officially as still we are communicating and working closely with Microsoft team to make this possible.

Another fact is the purpose of this community is not only for .Net Core conversion and we are planning to make EntLib alive again.

**Comment by ghd258** [comment]
This is good news, I think Microsoft is no longer maintained, I think the EF framework is good, but the large project is still better with the SQL statement, hoping to make Enterprise Library active and release the version as soon as possible.

**Comment by ghd258** [comment]
It's coming to the end of the month. Will it be finished before the end of the month?

**Comment by Chavoshi** [comment]
Sorry for the delay to update the packages, I will release them by early next week.

Regards,
@ghd258

**Comment by ghd258** [comment]
Anxiously waiting for the medium term, we hope to release the latest version as early as possible.
