### ISSUE TITLE
Upgrading from the Dll part of Nuget application to the latest version

### ISSUE THREAD

**Issue by ghd258** [EnterpriseLibrary/common-infrastructure#3]
Some Dlls from Nuget applications are not up-to-date, and it is recommended to upgrade to the latest version, such as System. Configuration. Configuration Manager, from 4.4.0 to 4.5.0

**Comment by Chavoshi** [comment]
All packages are updated now.
Please wait until the release announcement, as there might be a lot of committed before final release.
